name: Build Docker Image from rest-branch

on:
  push:
    branches: [ "rest-branch" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    services:
      docker:
        image: docker:latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: rest-branch
    - uses: docker/setup-buildx-action@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag flashcard-service:$(date +%s)          
    - name: Push Docker Image to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/flashcard-service:rest-branch
